# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.9, pypy-3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest
        if [ "${{ matrix.python-version }}" == "3.6" ]; then pip install mypy; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade git+https://github.com/mideind/GreynirPackage#egg=reynir
    - name: Type check with mypy
      run: |
        if [ "${{ matrix.python-version }}" == "3.6" ]; then mypy --python-version=3.6 *.py; fi
    - name: Test with pytest
      run: |
        python -m pytest
